[package]
name = "rebot"
version = "0.1.0"
edition = "2024"

[dependencies]
chromiumoxide = "0.7.0"
dotenvy = "0.15.7"
env_logger = "0.11.8"
futures = "0.3.31"
log = "0.4.27"
serde = "1.0.219"
serde_json = "1.0.140"
tokio = { version="1.46.1", features = ["full"] }
